version: '3.8'
services:
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data