"""create contacts and users tables

Revision ID: cb3bb8d06e55
Revises: e6296e12d3bd
Create Date: 2024-05-26 10:26:20.188088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3bb8d06e55'
down_revision: Union[str, None] = 'e6296e12d3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('contacts_owner_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.drop_column('contacts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_owner_id_fkey', 'contacts', 'users', ['owner_id'], ['id'])
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
